name: build and test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          #   global-json-file: global.json
          dotnet-version: 8
          dotnet-quality: "preview"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug --no-restore --verbosity normal

      - name: Test
        run: dotnet test --configuration Debug --no-build --verbosity normal
